### ISSUE TITLE
[Suggestion] Add a way to hide / close the CLI mid game.

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/Autorun-rs#18]
Small nitpicky suggestion but i might as well try.

Closing the console mid game currently results in:
![image](https://user-images.githubusercontent.com/69946827/140956304-8f2ee38c-5310-47bf-903b-ce708c66ea13.png)

It would add some QoL if you could close / hide it mid game so you don't have to have it open constantly. It currently makes tabbing into gmod annyoing and it would allow for a more permanent embed in gmod so you don't have to turn it on or off if you want to use it.

**Comment by Vurv78** [comment]
Do you mean to completely shut down Autorun or to just minimize / hide the cli to system tray?

**Comment by wrefgtzweve** [comment]
Imo, a way to hide / system tray the cli would be great. I don't see much of a reason to directly close it as it doesn't do much with input

**Comment by Vurv78** [comment]
It's currently there as a command and I disabled CTRL+C / 'x' button. Couldn't make it auto-minimize on close since windows consoles are horrible. Maybe in the future
