### ISSUE TITLE
[Bug] Couldn't create sautorun-rs dirs with path console spam

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/Autorun-rs#19]
At some point the console just starts spam filling with:
[ERROR] Couldn't create sautorun-rs dirs with path [C:\Users\USER\sautorun-rs\lua_dumps\20:33:06

No idea what triggers it, it seems to take a while for it to happen
spam is quite severe, this is a console log of mine https://pastebin.com/F9LRirGn

I replaced my actual file path name with USER if you're wondering.

**Comment by Vurv78** [comment]
It's usually issues with RunString paths / generally chunk names. Windows paths can't contain ":", they should be sanitized with the latest commit (There isn't a release for it though because of #17)

**Comment by Vurv78** [comment]
Note that there is a github actions artifact release though (Just that it didn't work for me ALSO with the same issue as #17)

**Comment by Vurv78** [comment]
Can you see if this persists with 0.6.0 now? Should be fixed

**Comment by possiblynova** [comment]
I'm getting the same error but with a different path, a bunch of these errors aswell.
```
05:16:04 [ERROR] Couldn't create sautorun-rs dirs with path [C:\Users\E1337\sautorun-rs\lua_dumps\��◄]�☺`4�V�☺♠\addons/wire/lua/wire/client/hlzasm]. [strings passed to WinAPI cannot contain NULs]
```

**Comment by Vurv78** [comment]
There have been significant changes in the recent beta updates so I'm assuming this is fixed. Please bug me here or on the discord if this comes up again or was not fixed.

> I'm getting the same error but with a different path, a bunch of these errors aswell.

That should be from this issue: https://github.com/Vurv78/Autorun-rs/issues/28
