### ISSUE TITLE
make it compatible with  "menu plugins redux"

### ISSUE THREAD

**Issue by YohSambre** [Vurv78/Autorun-rs#27]
I discovered this while browsing on github, it could be interesting for you to discover it

https://github.com/djsime1/menu-plugins-redux

much cleaner than the basic plugin system

**Comment by Vurv78** [comment]
Not sure what you want to be done here, this is just the rust binary module side, there's no lua. If anything this would be a issue for whatever uses Autorun, like https://github.com/Vurv78/Safety

Will still need to look into this though, looks nice.

**Comment by YohSambre** [comment]
with your skill level, I thought you could develop plugins in the future :p

**Comment by Vurv78** [comment]
I mean it would just be one line of lua. ``require("autorun")`` kind of excessive for a plugin

**Comment by Vurv78** [comment]
Closing this as sort of invalid unless you want to elaborate what you mean. Maybe setting up autorun to use a plugin system instead of having only two files?
