### ISSUE TITLE
the lua catcher has weaknesses (logs provided)

### ISSUE THREAD

**Issue by YohSambre** [Vurv78/Autorun-rs#28]
I noticed this on some servers, the filesteal doesn't catch anything and spam my external console

I uploaded the log part to anonfile because it was too big for pastebin..
[https://anonfiles.com/B0lcN6D1x1/January_26_2022_02-48_pm_log](url)

**Comment by Vurv78** [comment]
Might want to check out the 1.0.0-beta and see if it fixes it. Although right now finding other issues with it

**Comment by Vurv78** [comment]
There have been significant changes in the recent beta updates so I'm assuming this is fixed. Please bug me here or on the discord if this comes up again or was not fixed.
