### ISSUE TITLE
To be able to deactivate or activate the lua stealer at will

### ISSUE THREAD

**Issue by YohSambre** [Vurv78/Autorun-rs#29]
the title is quite explicit, it would be convenient to be able to sometimes disable the lua stealer via a command in the external console, personally I join a lot of server and it takes space on my disk

**Comment by Vurv78** [comment]
Note this is coming with the gui. I can make an option for the console with it as well tho

**Comment by Vurv78** [comment]
Also probably want a general "configs" file which will unify and be a third option for this in the autorun dir as a .toml file

**Comment by YohSambre** [comment]
> Note this is coming with the gui. I can make an option for the console with it as well tho

it would be really nice to be able to adjust it in the external console
