### ISSUE TITLE
Autorun-rs v1.0.0-beta failed injection problem

### ISSUE THREAD

**Issue by YohSambre** [Vurv78/Autorun-rs#30]
the last update seems to break, I inject and the external console does not appear yet the injector confirms me that the injection was a success,

I use extrem injector v3.7.3 , I am on the 64 bit version of gmod

**Comment by Vurv78** [comment]
I disabled injection for this update you need to use it as a binary module / include it from the menu as a menu plugin. Thought you already did this since you recommended that
