### ISSUE TITLE
PreInit loading breaks when you rejoin

### ISSUE THREAD

**Issue by Synkstar** [Vurv78/Autorun-rs#31]
Nothing more to explain just doesnt work correctly.

**Comment by YohSambre** [comment]
can you make an effort to describe your problem a little more?

**Comment by Synkstar** [comment]
I even tried compiling it myself but basically if you rejoin the server any detours you have break even that safety project he made. Or if someone kicks you and you rejoin. You have to restart your game for it to work again

**Comment by YohSambre** [comment]
I tested the last version and indeed there is a lot of crash without additional information

**Comment by Vurv78** [comment]
This is 0.7 correct? Will debug and make sure it's fixed by v1.

**Comment by Synkstar** [comment]
I tried compiling it from source too. Im using beta 1.0.0 right now. But it also had the problem on 0.7 so I tried compiling it to see if it was fixed or not

**Comment by Vurv78** [comment]
There have been significant changes in the recent beta updates so I'm assuming this is fixed. Please bug me here or on the discord if this comes up again or was not fixed.
