### ISSUE TITLE
Game crashing.

### ISSUE THREAD

**Issue by possiblynova** [Vurv78/Autorun-rs#34]
This keeps happening at seemingly random times, but here's 3 reports generated by Autorun

https://www.toptal.com/developers/hastebin/yoyiwefaha.properties

**Comment by Vurv78** [comment]
All caused by lua-patterns crate, probably https://github.com/stevedonovan/lua-patterns/issues/1.

Probably has to do with the ip corrupting for seemingly no reason so it's not really their fault, would be nice if it was able to be handled through a result instead of panicking though.

**Comment by YohSambre** [comment]
> All caused by lua-patterns crate, probably [stevedonovan/lua-patterns#1](https://github.com/stevedonovan/lua-patterns/issues/1).
> 
> Probably has to do with the ip corrupting for seemingly no reason so it might not really be their fault, would be nice if it was able to be handled through a result instead of panicking though.
> 
> Might take a while depending on if I want to go for the full and proper solution (get the ip through source sdk) or just fix my atomics

I confirm the crashes in the last version proposed, but I managed to capture this before the window left 

https://zupimages.net/up/22/05/08c5.png

except that I didn't get a log file for this crash..*sniff*

**Comment by possiblynova** [comment]
> All caused by lua-patterns crate, probably [stevedonovan/lua-patterns#1](https://github.com/stevedonovan/lua-patterns/issues/1).
Yeah, that I understood
> Probably has to do with the ip corrupting for seemingly no reason so it might not really be their fault, would be nice if it was able to be handled through a result instead of panicking though.
I was having problems on another server using the non-beta version where my console was spammed with Windows dir names not being able to have null characters
> Might take a while depending on if I want to go for the full and proper solution (get the ip through source sdk) or just fix my atomics
Yeah I know nothing about SourceSDK so I can't do anything there.

**Comment by Vurv78** [comment]
Could you try 1.0.0-beta2? Made significant changes.
https://github.com/Vurv78/Autorun-rs/actions/runs/1872694757

**Comment by Vurv78** [comment]
There have been significant changes in the recent beta updates so I'm assuming this is fixed. Please bug me here or on the discord if this comes up again or was not fixed.
