### ISSUE TITLE
Crashing whenever i leave a server

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/Autorun-rs#37]
After injecting or requiring autorun, leaving any server instantly crashes/closes my game. No warning no error.
The version i used is 0.7.0 latest release.

**Comment by Xandertron** [comment]
could try https://github.com/Vurv78/Autorun-rs/releases/tag/v1.0.0-beta and see if it crashes

**Comment by Vurv78** [comment]
Don't use 0.7.0. Get a build from the latest github workflow of 1.0.0-beta5

**Comment by Vurv78** [comment]
Also note 1.0.0 is switching the folder from sautorun-rs to just "autorun"

**Comment by Vurv78** [comment]
Closing since I closed the other issues for being fixed in the beta versions. https://github.com/Vurv78/Autorun-rs/actions/runs/1877444171. I'll make a release if I don't get to a stable version soon  (Only thing I want for 1.0.0 right now is 32 bit to be fixed.)
