### ISSUE TITLE
Spawnmenu Break + Game Crashing.

### ISSUE THREAD

**Issue by Hazeofdream** [Vurv78/Autorun-rs#38]
Happens on both the Latest official branch and latest beta branch.

Using x64 architecture release for both branches, x64 beta branch for the game as well, and obviously yes, my PC is x64 architecture.

Latest Log:
[March 02, 2022 04-11 pm.log](https://github.com/Vurv78/Autorun-rs/files/8173365/March.02.2022.04-11.pm.log)

Here is the configuration I use.
[cfg.zip](https://github.com/Vurv78/Autorun-rs/files/8173314/cfg.zip)

Only happened with the use of https://github.com/Vurv78/Safety May be coupled with this so I'm listing this here.

Interesting Note: No crashing happened if I loaded a singleplayer session and then went into a multiplayer, this also didn't affect gamemodes other than sandbox (I tried zombie survival)

**Comment by Vurv78** [comment]
You should be using a download from github actions, not from the releases, for bleeding edge. I'll make a release I guess, was initially holding off to fix 32 bit for it to be marked "stable"

**Comment by Hazeofdream** [comment]
I use many other github releases form other games, Releases is generally how I get my mods from all my shit excluding gmod addons like wire & acf.

**Comment by Vurv78** [comment]
Yeah I know it is my fault just wanted to let you know. Will add it on the README page, just telling you to note you get these "bleeding edge" releases from there.

(Also drafting a release.)
