### ISSUE TITLE
t pose and streched models

### ISSUE THREAD

**Issue by nooooo0** [Vurv78/Autorun-rs#42]
with autorun required from menu.lua and on a server with custom pms, models will be in a tpose and have extremly streched bone
![gmod_5QOmqUdxfx](https://user-images.githubusercontent.com/55218222/157772751-c1ba3545-f2bf-4120-bff5-30c907e9d603.png)
![gmod_4rjTmj43HF](https://user-images.githubusercontent.com/55218222/157772765-a0e8da1c-bf77-43ae-b0b4-5ab8f28f54b1.png)

**Comment by nooooo0** [comment]
actually noticed this affects ALL player models

**Comment by Vurv78** [comment]
U sure this isn't a Safety issue? Autorun doesn't interact with the lua state at all besides detouring loadbuffer for scripthook / file dumping

**Comment by nooooo0** [comment]
i moved my safety file out to test if it was safety causing it but it appears it wasnt

**Comment by Vurv78** [comment]
Closing for now since I have no clue what could be causing this. If it still happens would appreciate if you could dm me the ip of the server to look into it
