### ISSUE TITLE
Terminal colors don't work on windows 7

### ISSUE THREAD

**Issue by Andrew-Eathan** [Vurv78/Autorun-rs#50]
![image](https://user-images.githubusercontent.com/42521608/160236831-05857299-1d79-495c-8c76-f11497ef32b0.png)
probably because of color stuff, you could remove color prints if the OS is windows 7, though i know there's a way to print color

**Comment by YohSambre** [comment]
removing the colors is a bad idea, it would literally be a regression..there is surely a fix for this kind of problem

**Comment by Vurv78** [comment]
It uses truecolor (full rgb colors) right now which might not be supported by windows 7 I guess. 
I could make a build only using 8 bit terminal colors and see if that works for you. Otherwise yeah will need to make one without colors or have it as a setting

**Comment by Vurv78** [comment]
Yeah looks like it's only supported by windows 10 and above. Maybe you could try and see if you could enable it yourself somewhere while I get to it

**Comment by Vurv78** [comment]
You can disable colors now with the ``nocolor`` setting in your ``autorun/settings.toml`` file in the ``[autorun]`` section. Try that out @Andrew-Eathan

**Comment by Andrew-Eathan** [comment]
closing since you fixed it, thanks
