### ISSUE TITLE
Create new action in actions?

### ISSUE THREAD

**Issue by HikaruFox** [Vurv78/Autorun-rs#59]
Hello, i'd like to download autorun but i have got a little problem. I'm a linux user and i need the linux64 binaries but it says that the downloads are expired!

**Comment by Vurv78** [comment]
I've run another one, but linux is still not supported (which is why it's not in the previous releases and why #56 is open)
It *runs* but it doesn't do anything right now unfortunately ( didn't have a way to test it out since I use windows, might give it another try with WSL )

**Comment by wizard00000** [comment]
if you dont want to dualboot or anything like that and you're having issues with wsl then you could have a usb with a live iso on it and put garrys mod and steam on a partition and load the partition on the live iso to attempt running updates

**Comment by HikaruFox** [comment]
> I've run another one, but linux is still not supported (which is why it's not in the previous releases and why #56 is open) It _runs_ but it doesn't do anything right now unfortunately ( didn't have a way to test it out since I use windows, might give it another try with WSL )

Aight, ill just wait for linux support. I wish i could help, but i don't know anything about rust nor memory hacking :disappointed:
