### ISSUE TITLE
Legacy Browser/Console doesn't trigger JoinServer, so server ip is unknown

### ISSUE THREAD

**Issue by Xandertron** [Vurv78/Autorun-rs#6]
/title

win 10, 64-bit chromium

**Comment by Vurv78** [comment]
Potentially legacy browser not calling JoinServer, would have to find the underlying function that JoinServer calls that the legacy browser also uses, or something else idk.

**Comment by Vurv78** [comment]
Wont fix for now since I don't really know anyone who uses legacy browser and it'd be pretty annoying, Will maybe revisit it in the future though

**Comment by Vurv78** [comment]
New releases won't use this so not an issue.

**Comment by Xandertron** [comment]
cum
