### ISSUE TITLE
lua_openscript_cl does not open/run lua scripts

### ISSUE THREAD

**Issue by Aholicknight** [Vurv78/Autorun-rs#61]
```
lua_openscript_cl graphite.lua
ERROR  File does not exist: graphite.lua
```
![gmod_0972942783](https://user-images.githubusercontent.com/7843719/197419165-56dfcb3b-568a-4791-925d-7a69453010b9.png)

I am trying to run a lua script from the console but it says the file does not exist. What is the default path for lua scripts? Thank you!

**Comment by Vurv78** [comment]
It uses absolute paths, or (I believe only on bleeding edge / gha) resolves to paths in autorun/scripts/

**Comment by Vurv78** [comment]
That will work yes, it won't with quotes. So paths with spaces unfortunately won't work
