### ISSUE TITLE
Can you execute lua scripts with x32 autorun? 

### ISSUE THREAD

**Issue by Aholicknight** [Vurv78/Autorun-rs#63]
Due to problems, I am facing with the x64 build of Garry's Mod (unrelated to autorun-rs) I have to use the x32 build for most of the time.

I can succesfully inject autorun-rs into gmod but I noticed commands missing from the x32 build such as `lua_openscript_cl` and others.

Is there a reason why these commands are not available in the x32 version? Will they be added in at a future date? Thank you!

**Comment by Vurv78** [comment]
It's something internally that actually stopped autorun from running at all previously, but now just affects the lua running commands. I couldn't figure it out, and you really should use the 64 bit branch, so I haven't bothered to fix it.

What problems are you having with 64 bit? Have you tried https://github.com/solsticegamestudios/GModCEFCodecFix ?

**Comment by Aholicknight** [comment]
> It's something internally that actually stopped autorun from running at all previously, but now just affects the lua running commands. I couldn't figure it out, and you really should use the 64 bit branch, so I wasn't bothered to fix it.
> 
> What problems are you having with 64 bit? Have you tried [solsticegamestudios/GModCEFCodecFix](https://github.com/solsticegamestudios/GModCEFCodecFix) ?

@Vurv78 The problem I am having with the x64 build is this error: "Unable to initialize DirectSoundCapture. You won't be able to speak to other players." when I try to use voice chat.

**Comment by Aholicknight** [comment]
I will run the [GMODCEFCodecFix](https://bin.0xfc.de/?accac22997cb1711#CcvTM95bhSLUywtxra4st3XrrFLs8ttX3TsnJsWdY8ma) now and see if that fixes the problem I am having.
