### ISSUE TITLE
For the example hook.lua, how can I find 2 scripts?

### ISSUE THREAD

**Issue by Aholicknight** [Vurv78/Autorun-rs#64]
```lua
-- Replace all 'while true do end' scripts with 'while false do end' 😎
local script = Autorun.CODE
if script:find("while true do end") then
	Autorun.log("Found an evil script!")
	return string.Replace(script, "while true do end", "while false do end")
end
```

I would like to edit the example hook.lua to find `if !ply:IsAdmin()` and `if !LocalPlayer():IsStaff()` how would I do this? 

Thank you!

**Comment by Vurv78** [comment]
Fyi that won't do anything unless the server has really bad code trusting the client because you can't modify serverside files.

You can see the file structure for where `hook.lua` should go

**Comment by Aholicknight** [comment]
@Vurv78 The server I am on actually does have bad code, I did it with another script and I was able to access the custom debug menus.

And thank you, I will do what you suggested now

**Comment by Aholicknight** [comment]
@Vurv78 
> Also you could just modify the functions themselves, ie doing
> 
> ```lua
> debug.getregistry()["Player"].IsAdmin = function() return true end
> ```

So with this, what would the updated hook.lua be then?

**Comment by Vurv78** [comment]
You wouldn't need `hook.lua` if you did that, would just be using `autorun.lua`.

Also just found out that is a completely lua function that uses `Entity:GetNWString` internally, so you would actually do something like
```lua
local Entity = debug.getregistry().Entity

local old = Entity.GetNWString
function Entity:GetNWString(key, fallback)
    if key == "UserGroup" then return "superadmin" end
    return old(self, key, fallback)
end
```

**Comment by Aholicknight** [comment]
Thank you, I will see if this works.

**Comment by Aholicknight** [comment]
@Vurv78 Yup this works. Thank you! What would I have to add if I wanted to change ConVar's? (example: `TestingMode = CreateConVar( "gmt_testing", 0, { FCVAR_ARCHIVE, FCVAR_DONTRECORD, FCVAR_REPLICATED }, "GMT testing mode" )`) Is this even possible?

**Comment by Vurv78** [comment]
Assuming it's implemented in C, CreateConVar returns a ConVar object, you can override the value a convar has by changing the methods like `ConVar:GetInt()` depending on `ConVar:GetName()`.

Also ideally if you just want to mess with specific server scripts you could still use `hook.lua` to return modified versions of the scripts you manually make so you don't need to deal with hooking all these functions.
