### ISSUE TITLE
Add sautorun.require

### ISSUE THREAD

**Issue by Vurv78** [Vurv78/Autorun-rs#9]
Would allow for people to actually structure their code in modules rather than a massive single file. *Safety* is getting pretty huge

Still not sure about adding this kind of stuff because I'm afraid some might leak these to the global table where the functions could be abused.

**Comment by Vurv78** [comment]
When this is added I'll make it look local to a sautorun-rs/scripts dir rather than absolute

**Comment by Andrew-Eathan** [comment]
@Vurv78 wake
